apiVersion: v1
kind: Service
metadata:
  name: front-end-production
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: front-end-production
  type: ClusterIP